# Site settings
title: René is MAKING THINGS
header-img: img/home-bg.jpg
email: rene.bohne@gmail.com
description: "Personal website of René Bohne"
baseurl: "/"
url: "rene-bohne.de"
twitter_username: rene_bohne
github_username:  renebohne
facebook_username:  rene.bohne.aachen
youtube_username: renebohne
instagram_username: renebohne
linkedin_username: renebohne
# Build settings
markdown: kramdown
highlighter: rouge
#permalink: pretty
permalink:           /:title
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
plugins: [jekyll-paginate]
